apiBaseUrl=http://localhost:8111
apiVersion=/app/rest
user.token=eyJ0eXAiOiAiVENWMiJ9.SlV4eXo5TERoYzc3aFN6Ym5CLUpKaDQ4N0ZG.YjNmYjhkODItNGM1Mi00ZTllLTg5MzItOTAzYzRlZTZhYjNh

uiBaseUrl=http://localhost:8111
browser=chrome
browserSize=1920x1080
