apiBaseUrl=http://localhost:8111
apiVersion=/app/rest
# Super User can CREATE_USER / tokens. auto = token from docker container log
superuser.token=auto
superuser.docker.container=teamcity-server
uiBaseUrl=http://host.docker.internal:8111
uiRemote=http://localhost:4444/wd/hub
browser=chrome
browserSize=1920x1080