apiBaseUrl=http://localhost:8111
apiVersion=/app/rest

admin.username=admin
admin.password=admin

uiRemote=http://localhost:4444/wd/hub
uiBaseUrl=http://172.23.192.1:3000
browser=chrome
browserSize=1920x1080