# Format: RequestClass=ResponseClass:field1=field1Response,field2=field2Response
CreateUserRequest=UserResponse:username=username,name=name,email=email
CreateProjectRequest=ProjectResponse:name=name,id=id,description=description
CreateBuildTypeRequest=BuildTypeResponse:name=name,id=id
CreateBuildStepRequest=BuildStepResponse:name=name,type=type
RunBuildRequest=BuildResponse:buildTypeId=buildTypeId
AuthorizeAgentRequest=AgentResponse:status=authorized
