# Format: RequestClass=ResponseClass:field1=field1Response,field2=field2Response
NewProjectDescription=Project:name=name,id=id,description=description
BuildType=BuildType:name=name,id=id
Step=Step:name=name,type=type
Build=Build:buildTypeId=buildTypeId
AuthorizedInfo=Agent:status=authorized
