name: Checkstyle Verification

# Пайплайн запускается при каждом коммите (пуше)
on:
  push:
    branches: [ nikita_ci ]
  workflow_dispatch:

jobs:
  checkstyle:
    name: Code Quality Control
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Checkstyle Verification
        run: |
          echo "Запуск статического анализа кода автотестов"
          ./mvnw checkstyle:check
