name: Run tests

on:
  push:
  workflow_dispatch:

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '25'
          cache: 'maven'

      - name: Run Checkstyle
        run: mvn checkstyle:check